# Generated by Django 3.2 on 2021-05-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFGData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('gfg_handle', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField(default=0)),
                ('coding_score', models.IntegerField(default=0)),
                ('school', models.IntegerField(default=0)),
                ('basic', models.IntegerField(default=0)),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'GFG Data',
                'verbose_name_plural': 'GFG Data',
            },
        ),
    ]
