# Generated by Django 3.2 on 2021-05-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gfgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetcodeData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('leetcode_handle', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Leetcode Data',
                'verbose_name_plural': 'Leetcode Data',
            },
        ),
    ]
